# Generated by Django 5.0.2 on 2024-05-15 11:25

import ckeditor_uploader.fields
from django.db import migrations, models  

class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0003_artikel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='konten',
            field=models.TextField(), 
        ),
        migrations.AlterField(
            model_name='artikel',
            name='isi',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
