# Generated by Django 5.0.6 on 2024-05-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0004_artikel_konten_alter_artikel_isi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='konten',
        ),
    ]
